---
title: "LOL_Dataset_Project"
author: "Tamana Yaqoubi, Veronica Alviso"
date: "2025-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(gridExtra)

```

## Read csv files
```{r}
championTbl <- read.csv("ChampionTbl.csv")
itemTbl<- read.csv("ItemTbl.csv")
matchStatsTbl <- read.csv("MatchStatsTbl.csv")
matchTbl <- read.csv("MatchTbl.csv")
RankTbl <- read.csv("RankTbl.csv")
SummonerMatchTbl <- read.csv("SummonerMatchTbl.csv")
TeamMatchTbl <- read.csv("TeamMatchTbl.csv")
```

## View datasets
```{r}
head(championTbl) %>% knitr::kable()
head(itemTbl) %>% knitr::kable()
head(matchStatsTbl) %>% knitr::kable()
head(matchTbl) %>% knitr::kable()
head(RankTbl) %>% knitr::kable()
head(SummonerMatchTbl) %>% knitr::kable()
head(TeamMatchTbl) %>% knitr::kable()
```

## Including Plots

Create a new table that combines 



```{r}
itemTbl %>% 
  filter(ItemID == "2055")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


## Champion Table -VA





```{r}

```





## MSI Table -TY





```{r}

```





## match_rank Table -VA





```{r}

```





## TMM Tbl -TY




```{r}

```





## SMR tbl -VA





```{r}

```





